"""
Image Microservice

Input -- an integer contained in image-service.txt that was generated by PRNG.py
Output -- target file for main.py to open in the format "./pictures/$FILE_NAME

Limitations -- a folder entitled "pictures" with files must exist in the same file level as this file
            -- does not validate if the file chosen is a valid photo, or a supported one by the user's system
"""

import os


# create an array of photos in the ./pictures/ directory
pic_dir = os.listdir("./pictures")

# obtain number into working memory
with open("./image-service.txt", "r+") as f:
    number = f.read()

    try:
        number = int(number)
    except:
        raise TypeError

    # erase file
    f.truncate(0)
    f.seek(0)

    # create the path to the randomly selected file in ./pictures/
    path_to_file = f"./pictures/{pic_dir[number % len(pic_dir)]}"  # modulo cause I don't have 100 cat pictures from the internet

    f.write(path_to_file)
